---
version: 2

jobs:
  build:
    # Whenever the Go version is updated here, .travis.yml should also be
    # updated.
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/prometheus/prometheus
    resource_class: large

    steps:
    - checkout
    - run: |
          set -eu
          sudo apt install -y rsync
          ssh-keyscan farm.yourbase.io >> ~/.ssh/known_hosts
          rsync -e 'ssh -o BatchMode=yes' -L microclusters@farm.yourbase.io:/rembuild rembuild
          ./rembuild script
